apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent1.1-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: agent-volume-1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: teamcity
  name: agent1.1-volume
spec:
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: agent1.1-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi

